import Test from '@/components/Test';
import '../index.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className="py-4">
        <Test />
      </body>
    </html>
  );
}
